apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-k8s-back
  labels:
    app: mern-k8s
    component: back
spec:
  replicas: 2
  selector: 
    matchLabels:
      component: back
  template:
    metadata: 
      labels:
        app: mern-k8s
        component: back
    spec:
      containers:
        - name: mern-k8s-back
          image: venkatakrishnanraghavan/myytodo-back:latest
          ports: 
            - containerPort: 4000
          env: 
            - name: PORT
              value: "4000"
            - name: CONN_STR
              value: "$ATLAS_CONNECTION_STRING"
---
apiVersion: v1
kind: Service
metadata:
  name: mern-k8s-back
  labels:
    app: mern-k8s
    component: back
spec:
  type: LoadBalancer
  selector:
    component: back
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-k8s-front
  labels:
    app: mern-k8s
    component: front
spec:
  replicas: 2
  selector: 
    matchLabels:
      component: front
  template:
    metadata: 
      labels:
        app: mern-k8s
        component: front
    spec:
      containers:
        - name: mern-k8s-front
          image: venkatakrishnanraghavan/mytodo-front:latest
          ports: 
            - containerPort: 80
          
---
apiVersion: v1
kind: Service
metadata:
  name: mern-k8s-front
  labels:
    app: mern-k8s
    component: front
spec:
  type: LoadBalancer
  selector:
    component: front
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  externalIPs:
  - 192.168.49.2


